[build-system]
requires = ["hatchling>=1.27"]
build-backend = "hatchling.build"

[project]
name = "wumpiwave"
version = "0.1.0"
description = "An asynchronous media player library for Discord applications."
readme = "README.md"
requires-python = ">=3.13"
license = "MIT"
license-files = ["LICENSE"]
dependencies = [
    "aiohttp>=3.13,<4",
    "discord.py[voice]>=2.7.1,<3",
    "yt-dlp[default]"
]

[tool.hatch.build.targets.wheel]
packages = ["wumpiwave"]

exclude = [
    ".venv",
    "build",
    "dist",
]